# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Fondamenti di Informatica e Calcolo Numerico
email: matte.ragni@unitn.it
description: Appunti per il corso di Fondamenti di Informatica e Calcolo Numerico
tagline: Appunti per il corso di Fondamenti di Informatica e Calcolo Numerico
baseurl: ""
url: ""
paginate: 1

author:
  name: Matteo Ragni
  url: mailto:matteo.ragni@unitn.it

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
# theme: minima
theme: jekyll-theme-cayman
exclude:
  - Gemfile
  - Gemfile.lock
  - _posts/2015-02-06-virtual-machine.markdown
  - _posts/solutions/2017-02-21-soluzione-.markdown
encoding: utf-8
